version: '3'

volumes:
  container_db:

services: 

    # PROXY NGINX
    web:
      image:
      ports:
      - 8080:80
      volumes:
      - ./nginx/:/usr/share/nginx/html/
    
    # APP    
    nodeapp:
      image: 
      volumes:
      - ./nodeapp/:/usr/src/app/
    
    # BANCO    
    # db:
    #   image: mongo
    #   restart: always
    #   tty: true
    #   volumes: 
    #     - container_db:/data/db
    #   ports: 
    #     - "5432:5432"

    # # CONSOLE WEB DO BANCO  
    # adminMongo:
    #   image: "mrvautin/adminmongo"
    #   tty: true
    #   environment: 
    #     - DB_HOST=db
    #     - DB_PORT=27017
    #     - HOST=0.0.0.0
    #   ports: 
    #     - 1234:1234
    #   depends_on: 
    #     - db    

    # CONSOLE WEB PARA GERENCIAR CONTAINER
    portainer:
      image: portainer/portainer-ce
      restart: always
      tty: true
      ports: 
        - "8000:8000"
        - "9001:9000"
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock 
        - /portainer_data:/data