name: Deploy to Staging 

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#workflows-notifications'
      if: always()

    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    #configure credenciais do provedor
    #criar repositorio para guardar a imagem
    #build e tag da imagem
    #push da imagem
    