name: Deploy to Staging 

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: starting
        channel: '#workflows-notifications'
      if: always()

    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    
    - name: Import Secrets 
      id: secrets
      uses: hashicorp/vault-action@v2.3.1
      with:
        url: ${{ secrets.VAULT_URL }}
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          secrets/dockerhub/ username
          secrets/dockerhub/ token 
    - name: Set up QEMU
      id: seupt-qemu
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      id: setup-docker
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Dockerhub
      id: docker-login
      uses: docker/login-action@v1
      with:
        username: ${{ steps.secrets.outputs.username }}
        password: ${{ steps.secrets.outputs.token }}
     
    - name: Build and push
      id: docker-build-push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.secrets.outpus.username }}/nodeapp:latest

        
    #importar secrets do vault para consumir no workflow
    #configure credenciais do provedor
    #criar repositorio para guardar a imagem
    #build e tag da imagem
    #push da imagem
    
